kiska/TheChaperone/urls.py
from django.urls import path
from .views import index, ad_report_pdf, brands, create, profile, login, \
    logout, guest, edit_user, create_ad, car_detail, registration, ad_report, \
    brand_view, edit_ad, about

urlpatterns = [
    path('', index, name='home'),
    path('create', create, name='create'),
    path('brands', brands, name='brands'),
    path('profile', profile, name='profile'),
    path('login', login, name='login'),
    path('logout/', logout, name='logout'),
    path('guest/', guest, name='guest'),
    path('edit_user/<int:user_id>/', edit_user, name='edit_user'),
    path('create_ad', create_ad, name='create_ad'),
    path('car/<int:car_id>/', car_detail, name='car_detail'),
    path('registration', registration, name='registration'),
    path('ad_report_pdf', ad_report_pdf, name='ad_report_pdf'),
    path('ad_report_form', ad_report, name='ad_report'),
    path('brand/<str:name_Mark>/', brand_view, name='brand'),
    path('edit_ad/<int:ad_id>/', edit_ad, name='edit_ad'),
    path('about', about, name='about'),


]

kiska/kiska/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TheChaperone.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kiska/TheChaperone/models.py
from django.db import models
from .services import photo_сar
# Create your models here.


class Mark(models.Model):
    id_Mark = models.AutoField(primary_key=True)
    name_Mark = models.CharField(max_length=50)
    photo_Mark = models.ImageField(upload_to='photo_mark', null=True, blank=True)

    def __str__(self):
        return self.name_Mark

    class Meta:
        db_table = "Mark"


class Models(models.Model):
    id_Mod = models.AutoField(primary_key=True)
    name_Mark = models.ForeignKey(Mark, on_delete=models.CASCADE)
    name_Mod = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Mod

    class Meta:
        db_table = "Models"


class Roles(models.Model):
    id_Roles = models.AutoField(primary_key=True)
    name_Roles = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Roles

    class Meta:
        db_table = "Roles"


class CarCat(models.Model):
    id_CarCat = models.AutoField(primary_key=True)
    name_Cat = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Cat

    class Meta:
        db_table = "CarCat"


class City(models.Model):
    id_City = models.AutoField(primary_key=True)
    name_City = models.CharField(max_length=50)

    def __str__(self):
        return self.name_City

    class Meta:
        db_table = "City"


class Metro(models.Model):
    id_Met = models.AutoField(primary_key=True)
    name_City = models.ForeignKey(City, on_delete=models.CASCADE)
    name_Met = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Met

    class Meta:
        db_table = "Metro"


class Color(models.Model):
    id_Color = models.AutoField(primary_key=True)
    name_Color = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Color

    class Meta:
        db_table = "Color"


class Transmission(models.Model):
    id_Trans = models.AutoField(primary_key=True)
    name_Trans = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Trans

    class Meta:
        db_table = "Transmission"


class Handlebar(models.Model):
    id_Hand = models.AutoField(primary_key=True)
    name_Hand = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Hand

    class Meta:
        db_table = "Handlebar"


class Wheeldrive(models.Model):
    id_Wheel = models.AutoField(primary_key=True)
    name_Wheel = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Wheel

    class Meta:
        db_table = "Wheeldrive"


class Bodywork(models.Model):
    id_Body = models.AutoField(primary_key=True)
    name_Body = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Body

    class Meta:
        db_table = "Bodywork"


class DamageStatus(models.Model):
    id_Dam = models.AutoField(primary_key=True)
    name_Dam = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Dam

    class Meta:
        db_table = "DamageStatus"


class AdStatus(models.Model):
    id_AdStat = models.AutoField(primary_key=True)
    name_AdStat = models.CharField(max_length=50)

    def __str__(self):
        return self.name_AdStat

    class Meta:
        db_table = "AdStatus"


class FuelType(models.Model):
    id_Fuel = models.AutoField(primary_key=True)
    name_Fuel = models.CharField(max_length=50)

    def __str__(self):
        return self.name_Fuel

    class Meta:
        db_table = "FuelType"


class TypeOfEngine(models.Model):
    id_TypeEng = models.AutoField(primary_key=True)
    name_TypeEng = models.CharField(max_length=50)

    def __str__(self):
        return self.name_TypeEng

    class Meta:
        db_table = "TypeOfEngine"


class Engine(models.Model):
    id_Engine = models.AutoField(primary_key=True)
    name_Engine = models.CharField(max_length=50)
    hp_Engine = models.IntegerField(default=1)
    fuel_Engine = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    type_Engine = models.ForeignKey(TypeOfEngine, on_delete=models.CASCADE)
    capacity_Engine = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return f"{self.name_Engine} {self.hp_Engine} {self.capacity_Engine}"

    class Meta:
        db_table = "Engine"


class UserStatus(models.Model):
    id_UserStat = models.AutoField(primary_key=True)
    name_UserStat = models.CharField(max_length=50)

    def __str__(self):
        return self.name_UserStat

    class Meta:
        db_table = "UserStatus"


class User(models.Model):
    id_User = models.AutoField(primary_key=True)
    log_User = models.CharField(max_length=50)
    pass_User = models.CharField(max_length=50)
    phone_User = models.CharField(max_length=50)
    email_User = models.CharField(max_length=50)
    city_User = models.ForeignKey(City, on_delete=models.CASCADE)
    name_User = models.CharField(max_length=50)
    surname_User = models.CharField(max_length=50)
    birth_User = models.DateField()
    role_User = models.ForeignKey(Roles, on_delete=models.CASCADE)
    status_User = models.ForeignKey(UserStatus, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.log_User} {self.pass_User} {self.phone_User} {self.email_User} {self.name_User} {self.surname_User} {self.birth_User}"

    class Meta:
        db_table = "User"


class Car(models.Model):
    id_Car = models.AutoField(primary_key=True)
    vin_Car = models.CharField(max_length=50)
    model_Car = models.ForeignKey(Models, on_delete=models.CASCADE)
    year_Car = models.DateField()
    statenum_Car = models.CharField(max_length=50)
    cat_Car = models.ForeignKey(CarCat, on_delete=models.CASCADE)
    color_Car = models.ForeignKey(Color, on_delete=models.CASCADE)
    trans_Car = models.ForeignKey(Transmission, on_delete=models.CASCADE)
    handle_Car = models.ForeignKey(Handlebar, on_delete=models.CASCADE)
    wheel_Car = models.ForeignKey(Wheeldrive, on_delete=models.CASCADE)
    engine_Car = models.ForeignKey(Engine, on_delete=models.CASCADE)
    numown_Car = models.IntegerField(default=1)
    body_Car = models.ForeignKey(Bodywork, on_delete=models.CASCADE)
    mileage_Car = models.IntegerField(default=1)
    damage_Car = models.ForeignKey(DamageStatus, on_delete=models.CASCADE)
    photo_Car = models.ImageField(upload_to='photo_сar', null=True, blank=True)
    user_Car = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.vin_Car} {self.year_Car} {self.statenum_Car} {self.numown_Car} {self.mileage_Car}"

    class Meta:
        db_table = "Car"


class Advertisment(models.Model):
    id_Ad = models.AutoField(primary_key=True)
    user_Ad = models.ForeignKey(User, on_delete=models.CASCADE)
    car_Ad = models.ForeignKey(Car, on_delete=models.CASCADE)
    comm_Ad = models.CharField(max_length=280)
    date_Ad = models.DateField()
    loc_Ad = models.ForeignKey(Metro, on_delete=models.CASCADE)
    status_Ad = models.ForeignKey(AdStatus, on_delete=models.CASCADE)
    price_Ad = models.DecimalField(max_digits=20, decimal_places=2)
    contact_Ad = models.CharField(max_length=140)

    def __str__(self):
        return f"{self.comm_Ad} {self.date_Ad} {self.price_Ad} {self.contact_Ad}"

    class Meta:
        db_table = "Advertisment"

kiska/TheChaperone/templates/about.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>The Chaperone</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="../../css/editor.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="#">The Chaperone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Домашняя <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brands' %}">Бренды</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create' %}">Создать объявление</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <button type="button" class="btn btn-outline-success my-2 my-sm-0" onclick="window.location.href='{% url 'profile' %}'">Профиль</button>
          </form>
        </div>
      </nav>
    </header>
<div class="container">


      <div class="jumbotron">
        <h1 class="display-3">The Chaperone</h1>
        <p class="lead">Хотите купить машину быстро и безопасно? Вам к нам, ведь на нашем сайте уже {{ ad_count }} активных объявлений!</p>
        <p><a class="btn btn-lg btn-success" href="{% url 'home' %}" role="button">Каталог</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Хотите быстро продать свой подержанный автомобиль?</h4>
          <p>Мы - платформа которая предоставляет пользователям удобную площадку для продажи их подержанных авто</p>

          <h4>Ищете автомобиль мечты по выгодной цене?</h4>
          <p>Использование нашего сервиса абсолютно бесплатно, имеется круглосуточная поддержка</p>
        </div>

        <div class="col-lg-6">
          <h4>Желаете получить круглосуточную поддержку и помощь?</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Хотите обменять свой автомобиль на другой?</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>


        </div>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Мы - платформа, которая поможет вам решить любые вопросы, связанные с продажей или покупкой подержанных автомобилей. На нашей <br>&nbsp;&nbsp;&nbsp;площадке вы найдете широкий выбор автомобилей разных марок и моделей по выгодным ценам. Мы гарантируем быструю и безопасную сделку, &nbsp;&nbsp;&nbsp;а также круглосуточную поддержку и консультации наших специалистов. Не упустите свой шанс получить максимальную выгоду от продажи или &nbsp;&nbsp;&nbsp;покупки автомобиля с нами!
        </p>
      </div>


    </div>


      <!-- FOOTER -->
      <footer class="container">

        <p>© 2017-2018 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer>

    </main>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="../../js/vendor/popper.min.js"></script>
    <script src="../../js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/holderjs@2.9.4/holder.js"></script>
    <svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="25" style="font-weight:bold;font-size:25pt;font-family:Arial, Helvetica, Open Sans, sans-serif">500x500</text></svg></body>
</html>

kiska/TheChaperone/templates/ad_report_pdf.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Ad Report Form</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  </head>
  <body>
  <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="#">The Chaperone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Домашняя <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brands' %}">Бренды</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create' %}">Создать объявление</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <button type="button" class="btn btn-outline-success my-2 my-sm-0" onclick="window.location.href='{% url 'profile' %}'">Профиль</button>
          </form>
        </div>
      </nav>
    </header>
   <div class="container mt-4">
    <form method="post" action="{% url 'ad_report' %}">
      {% csrf_token %}
      <div class="container">
        <div class="form-group row justify-content-center">
          <label for="start_date" class="col-sm-2 col-form-label">Начальная дата:</label>
          <div class="col-sm-4">
            <input type="date" id="start_date" name="start_date" class="form-control" required>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <label for="end_date" class="col-sm-2 col-form-label">Конечная дата:</label>
          <div class="col-sm-4">
            <input type="date" id="end_date" name="end_date" class="form-control" required>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary btn-block">Создать отчет</button>
          </div>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary btn-block" formaction="{% url 'ad_report_pdf' %}">Создать PDF</button>
          </div>
        </div>
      </div>
    </form>
  </div>
    <script src="<https://code.jquery.com/jquery-3.3.1.slim.min.js>"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="<https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js>"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNSbNtB"
      crossorigin="anonymous"></script>
    <script src="<https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js>"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
  </body>
</html>

kiska/TheChaperone/templates/create.html
<!DOCTYPE html>
<html>
  <head>
    <title>Создание объявления</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="<https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css>">
      <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'about' %}">The Chaperone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Домашняя <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brands' %}">Бренды</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create' %}">Создать объявление</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <button type="button" class="btn btn-outline-success my-2 my-sm-0" onclick="window.location.href='{% url 'profile' %}'">Профиль</button>
          </form>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
              <label for="id_model_Car">Модель автомобиля:</label>
              <select name="model_Car" id="id_model_Car" class="form-control" required>
                  {% for model in models %}
                      <option value="{{ model.id_Mod }}">{{ model.name_Mark }} {{ model.name_Mod }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_cat_Car">Категория автомобиля:</label>
              <select name="cat_Car" id="id_cat_Car" class="form-control" required>
                  {% for cat in carcats %}
                      <option value="{{ cat.id_CarCat }}">{{ cat.name_Cat }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_color_Car">Цвет автомобиля:</label >
              <select name="color_Car" id="id_color_Car" class="form-control" required>
                  {% for color in colors %}
                      <option value="{{ color.id_Color }}">{{ color.name_Color }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_trans_Car">Коробка передач:</label>
              <select name="trans_Car" id="id_trans_Car" class="form-control" required>
                  {% for trans in transmissions %}
                      <option value="{{ trans.id_Trans }}">{{ trans.name_Trans }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_handle_Car">Руль:</label>
              <select name="handle_Car" id="id_handle_Car" class="form-control" required>
                  {% for handle in handles %}
                      <option value="{{ handle.id_Hand }}">{{ handle.name_Hand }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_wheel_Car">Привод:</label>
              <select name="wheel_Car" id="id_wheel_Car" class="form-control" required>
                  {% for wheel in wheeldrives %}
                      <option value="{{ wheel.id_Wheel }}">{{ wheel.name_Wheel }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_engine_Car">Двигатель:</label>
              <select name="engine_Car" id="id_engine_Car" class="form-control" required>
                  {% for engine in engines %}
                      <option value="{{ engine.id_Engine }}">{{ engine.name_Engine }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_body_Car">Кузов:</label>
              <select name="body_Car" id="id_body_Car" class="form-control" required>
                  {% for body in bodyworks %}
                      <option value="{{ body.id_Body }}">{{ body.name_Body }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_damage_Car">Повреждения:</label>
              <select name="damage_Car" id="id_damage_Car" class="form-control" required>
                  {% for damage in damagestatuses %}
                      <option value="{{ damage.id_Dam }}">{{ damage.name_Dam }}</option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
              <label for="id_vin_Car">VIN код:</label>
              <input type="text" name="vin_Car" id="id_vin_Car" class="form-control" required>
          </div>
          <div class="form-group">
              <label for="id_year_Car">Год выпуска:</label>
              <input type="date" name="year_Car" id="id_year_Car" class="form-control" required>
          </div>
          <div class="form-group">
              <label for="id_statenum_Car">Гос. номер:</label>
              <input type="text" name="statenum_Car" id="id_statenum_Car" class="form-control" required>
          </div>
          <div class="form-group">
              <label for="id_numown_Car">Количество владельцев:</label>
              <input type="text" name="numown_Car" id="id_numown_Car" class="form-control" required>
          </div>
          <div class="form-group">
              <label for="id_photo_Car">Фото автомобиля:</label>
              <input type="file" name="photo_Car" id="id_photo_Car" class="form-control" required>
          </div>
          <button type="submit" class="btn btn-primary">Создать объявление</button>
        </form>
      </div>
    </main>
    <script src="<https://code.jquery.com/jquery-3.5.1.slim.min.js>"></script>
    <script src="<https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js>"></script>
    <script src="<https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js>"></script>
  </body>
</html>

kiska/TheChaperone/templates/create_ad.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Добавление объявления</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'about' %}">The Chaperone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Домашняя <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brands' %}">Бренды</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create' %}">Создать объявление</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <button type="button" class="btn btn-outline-success my-2 my-sm-0" onclick="window.location.href='{% url 'profile' %}'">Профиль</button>
          </form>
        </div>
      </nav>
    </header>
<main>
    <div class="container">
        <h1 class="text-center my-5">Добавление объявления</h1>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post" action="{% url 'create_ad' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="comm_Ad">Комментарий:</label>
                                <textarea  id="comm_Ad" name="comm_Ad" class="form-control" maxlength="280"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="metro_Ad">Местоположение:</label>
                                <select class="form-control" id="metro_Ad" name="metro_Ad">
                                    {% for metro in metros %}
                                    <option value="{{ metro.id_Met }}">{{ metro.name_Met }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="car_Ad">Машина:</label>
                                <select class="form-control" id="car_Ad" name="car_Ad">
                                    {% for car in cars %}
		                            {% if car.user_Car == user %}
		                            <option value="{{ car.id_Car }}">{{ car.model_Car.name_Mark }} {{car.model_Car.name_Mod}} {{car.statenum_Car}}</option>
                                    {% endif %}
		                            {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="price_Ad">Цена:</label>
                                <input type="text" id="price_Ad" name="price_Ad" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="contact_Ad">Ник в Telegram (без @):</label>
                                <input type="text" id="contact_Ad" name="contact_Ad" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="hidden" name="user_Ad" id="id_user_Ad" class="form-control" value="1">
                                <input type="hidden" name="date_Ad" id="id_date_Ad" class="form-control" value="2022-09-23">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<script src="jquery-3.5.1.slim.min.js"></script>
<script src="popper.min.js"></script>
<script src="bootstrap.min.js"></script>
</body>
</html>

kiska/TheChaperone/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{% block content %}
<h2>Ошибка</h2>
<p>{{ message }}</p>
{% endblock %}

</body>
</html>